# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    ubuntu:
        name: ubuntu Job
        runs-on: ubuntu-latest
        steps:
        - run: date
    windows:
        name: windows Job
        runs-on: windows-latest
        steps:
        - run: date
     macos:
        name: macos Job
        runs-on: macos-latest
        steps:
        - run: date
    depends:
        needs: [ubuntu,windows,macos]
        runs-on: windows-latest
        steps:
        - run: date